# Generated by Django 5.0.4 on 2024-04-07 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0003_alter_story_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storystream',
            name='story',
        ),
        migrations.AddField(
            model_name='storystream',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stories.story'),
        ),
    ]
