# Generated by Django 5.0 on 2024-01-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_auto_20231216_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
