# Generated by Django 5.0 on 2024-01-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0006_remove_profile_is_private_delete_otptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.CharField(default='public', max_length=20),
        ),
    ]
