# Generated by Django 5.0 on 2024-01-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0008_alter_profile_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_private',
            field=models.CharField(blank=True, default='public', max_length=20, null=True),
        ),
    ]
