# Generated by Django 4.2.9 on 2024-02-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0010_remove_profile_created_remove_profile_is_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
