# Generated by Django 4.2.9 on 2024-02-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0012_alter_profile_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.CharField(default='public', max_length=7),
        ),
    ]
