# Generated by Django 4.2.9 on 2024-02-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_remove_post_picture_postfilecontent_post_picture'),
        ('authy', '0014_alter_profile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, to='Post.post'),
        ),
    ]
