# Generated by Django 4.2.9 on 2024-02-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0015_alter_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_send_notifications',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
